type: workflow
name: cidr_recon
alias: cidrrec
description: Local network recon
tags: [recon, cidr, network]
input_types:
  - cidr_range
tasks:
  mapcidr:
    description: Find CIDR range IPs
    # record_results: False
  fping:
    description: Check for alive IPs
    targets_: ip.ip
results:
  - type: ip
    condition: item.alive
