type: workflow
name: host_recon
alias: hostrec
description: Host recon
tags: [recon, network, http]
input_types:
  - host
  - cidr_range
tasks:
  naabu:
    description: Find open ports
    ports: "-"  # scan all ports
  nmap:
    description: Search for vulnerabilities on open ports
    skip_host_discovery: True
    version_detection: True
    script: vulners
    targets_: port.host
    ports_: port.port
  httpx:
    description: Probe HTTP services on open ports
    targets_:
      - type: port
        field: '{host}:{port}'
        condition: item._source == 'nmap'
  _group:
    nuclei/network:
      description: Scan network and SSL vulnerabilities
      tags: [network, ssl]
    nuclei/url:
      description: Search for vulnerabilities on alive HTTP services
      exclude_tags: [network, ssl, file, dns, osint, token-spray, headers]
      targets_:
        - type: url
          field: url
          condition: item.status_code != 0
  # _group:
  #   searchsploit/port:
  #     description: Search for related exploits (port service)
  #     targets_:
  #     - type: port
  #       field: '{host}~{service_name}'
  #       condition: item._source == 'nmap' and len(item.service_name.split('/')) > 1
  #   searchsploit/vuln:
  #     description: Search for related exploits (vulns)
  #     targets_:
  #     - type: vulnerability
  #       field: '{matched_at}~{id}'
  #       condition: item.id

results:
  - type: port
    condition: item._source == 'nmap'

  - type: vulnerability
  #   condition: item.confidence == 'high'

  - type: url
    condition: item.status_code != 0
